services:
  db:
      image: postgres:latest
      container_name: FSQuizDB
      environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: password
        POSTGRES_DB: FSQuizDB
      ports:
        - "5432:5432"
      volumes:
        - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
