services:
  quiz-backend:
      build:
        context: .
      environment:
        DATABASE_URL: postgresql://admin:password@db:5432/postgres
        PORT: 3000
      ports:
        - 3000:3000
      depends_on:
      - db

volumes:
  db-data:
